server:
  port: 8005
mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: jdbc,log
  application:
    name: pocaccount
  sleuth:
    sampler:
      probability: 0.1 #sleth采样 0.1表示采样10% 1表示全部采样
  zipkin:
    base-url: http://local056.xiaogj.com:9411/  #整合zipkin
    service:
      name: pocaccount  #zipkin中显示的名称
    sender:
      type: web
  cloud:
    stream:
      rabbit:
        bindings:
          xgj-point-topic:
            consumer:
              exchangeDurable: true
              exclusive: false
              anonymousGroupPrefix: pocpoint.
              exchangeAutoDelete: false
              durableSubscription: true
              acknowledge-mode: MANUAL
      binders:
        default:
          type: rabbit
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: local059.xiaogj.com
                port: 5672
                username: admin
                password: '{cipher}5d51c8d7a9e6ffdc2fbcb4f5a6ead28001b6026d76db3e809f24cddccce5fbc7'
                virtual-host: xiaogj_sit_msg
      bindings:
        xgj-point-topic:
          destination: xgj-point-topic  #exchange名称，交换模式默认是topic
          content-type: application/json
          group: pocpoint
eureka:
  client:
    register-with-eureka: true #是否注册要eureka
    service-url:
      defaultZone: http://xiaogj:xiaogj@local056.xiaogj.com:8761/eureka #erueka地址
  instance:
    instance-id: pocaccount  #eureka显示的实例名称
    prefer-ip-address: true #ip注册
swagger:
  enable: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 200 #并发执行的最大线程数，默认10
      maxQueueSize: 200 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      fallback:
        # 是否开启回退方法
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000
ribbon:
  ReadTimeout: 20000 # 处理时间
  ConnectTimeout: 20000 # 连接时间
  MaxAutoRetries: 0 #最大自动重试次数
  MaxAutoRetriesNextServer: 1 # 换实例重试次数
  MaxTotalHttpConnections: 2000 # 最大http连接数，越大越好，但到到达一个临界点之后，就不会提高响应速度了
  MaxConnectionsPerHost: 1000 # 每个host连接数



