server:
  port: 8006
mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: xiaogj_tx_group
  profiles:
    active: jdbc,log
  application:
    name: pocstudent
  sleuth:
    sampler:
      probability: 0.1  #采样频率
  zipkin:
    base-url: http://local056.xiaogj.com:9411/
    service:
      name: student
    sender:
      type: web
eureka:
  client:
    register-with-eureka: true #是否注册要eureka
    service-url:
      defaultZone: http://xiaogj:xiaogj@local056.xiaogj.com:8761/eureka #erueka地址
  instance:
    instance-id: pocstudent:${server.port}  #eureka显示的实例名称
    prefer-ip-address: true #ip注册
swagger:
  enable: true
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 200 #并发执行的最大线程数，默认10
      maxQueueSize: 200 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      fallback:
        # 是否开启回退方法
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000
ribbon:
  ReadTimeout: 20000 # 处理时间
  ConnectTimeout: 20000 # 连接时间
  MaxAutoRetries: 0 #最大自动重试次数
  MaxAutoRetriesNextServer: 1 # 换实例重试次数
  MaxTotalHttpConnections: 2000 # 最大http连接数，越大越好，但到到达一个临界点之后，就不会提高响应速度了
  MaxConnectionsPerHost: 1000 # 每个host连接数

seata:
  enabled: true
  application-id: pocstudent
  tx-service-group: xiaogj_tx_group
    #enable-auto-data-source-proxy: true
    #use-jdk-proxy: false
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    default:
      grouplist: local033.xiaogj.com:8091
      #enable-degrade: false
      #disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true


