server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://xiaogj:xiaogj@localhost:8761/eureka
  instance:
    instance-id: gateway
    prefer-ip-address: true
spring:
  application:
    name:  gateway
  sleuth:
    sampler:
      probability: 1  #采样频率
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: gateway
    sender:
      type: web
logging:
  config: classpath:logback.xml
  path: /data/logs/${spring.application.name}
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
security:
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login
    client:
      access-token-uri: http://authserver:8290/oauth/token #令牌端点
      user-authorization-uri: http://authserver:8290/oauth/authorize #授权端点
      client-id: zuul #OAuth2客户端ID
      client-secret: zuul_123 #OAuth2客户端密钥
    resource:
      #token-info-uri: http://authserver:8290/oauth/authorize
      jwt:
        #key-store: xiaogj-jwt.jks
        #key-store-password: xiaogj123
        #key-alias: xiaogj-jwt
        key-value: xiaogj123 #使用对称加密方式，默认算法为HS256
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  # 添加代理头
  add-proxy-headers: true
  # 敏感头信息（重要）
  sensitive-headers: [Cookie, Set-Cookie]
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

#zuul:
#  routes:
#    users:
#      path: /users-proxy/**
#      serviceId: microcloud-provider-users
#    users2:
#      path: /users2-proxy/**
#      url: http://localhost:8090/
#    product:
#      path: /product-proxy/**
#      serviceId: microcloud-provider-product