server:
  port: 8001
spring:
  application:
    name: billing
  sleuth:
    sampler:
      probability: 1  #采样频率
  zipkin:
    base-url: http://127.0.0.1:9411/
    service:
      name: live
    sender:
      type: web
eureka:
  client:
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://xiaogj:xiaogj@127.0.0.1:8761/eureka
  instance:
    instance-id: billing
    prefer-ip-address: true
logging:
  config: classpath:logback.xml
  path: /data/logs/${spring.application.name}
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
