spring:
  datasource:
    url: jdbc:mysql://xdevp.xiaogj.com:3306/xiaogjtest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8 # 数据库连接地址
    username: xiaogj # 数据库用户名
    password: xiaogj!@# # 数据库连接密码