server:
 port: 8004
mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml
spring:
 application:
   name: guide
   sleuth:
     sampler:
       probability: 1 #sleth采样 0.1表示采样10% 1表示全部采样
   zipkin:
     base-url: http://localhost:9411/  #整合zipkin
     service:
       name: guide  #zipkin中显示的名称
     sender:
       type: web
 datasource:
   url: jdbc:mysql://xdevp.xiaogj.com:3306/xiaogjtest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8 # 数据库连接地址
   username: xiaogj # 数据库用户名
   password: xiaogj!@# # 数据库连接密码
eureka:
  client:
    register-with-eureka: true #是否注册要eureka
    service-url:
      defaultZone: http://xiaogj:xiaogj@127.0.0.1:8761/eureka #erueka地址
  instance:
    instance-id: guide  #eureka显示的实例名称
    prefer-ip-address: true #ip注册
logging:
  config: classpath:logback.xml #log日志配置
  path: /data/logs/${spring.application.name} #日志存放文件夹
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
#积分规则
point:
  rules:
    StudentLogin: 100  #学员登陆成功加10分
    TeacherLogin: 105  #老师登陆成功加10分
    StudentAdd: 5   #老师新增学员成功加5分
    StudentDel: -5   #老师删除学员减5分
